"use strict";
var tr = React.createFactory("tr");
var th = React.createFactory("th");
var td = React.createFactory("td");
var div = React.createFactory("div");
var label = React.createFactory("label");
var center = React.createFactory("center");
var input = React.createFactory("input");
var button = React.createFactory("button");
var link = React.createFactory("a");
var p = React.createFactory("p");
var span = React.createFactory("span");
var br = React.createFactory("br");
var small = React.createFactory("small");
var table = React.createFactory("table");
var tbody = React.createFactory("tbody");
var thead = React.createFactory("thead");
